### ISSUE TITLE
Output generated C++ code

### ISSUE THREAD

**Issue by ArcaneEngineer** [NectarJS/nectarjs#103]
Fantastic idea, by the way!

I would like to be able to generate code (preferably C, but if not then C++) for each platform, from JS. I would then like to be able to go into each platform's C/C++ code and make platform-specific optimisations.

Is there any reason not to output the intermediate C/C++ code, at present?

**Comment by adrien-thierry** [comment]
Hi @ArcaneEngineer ,
Thank you !

You can output c++ code without compilation by using `--generate`

You can change the output directory with `--tmp`

**Comment by adrien-thierry** [comment]
@ArcaneEngineer is it ok ?
