### ISSUE TITLE
Async compilation error

### ISSUE THREAD

**Issue by InDIOS** [NectarJS/nectarjs#112]
Hi @adrien-thierry, how are you. There is an error when i try to compile async example. This is the error:
```
In file included from C:\Users\Robert\Desktop\test-njs\.nectar\umnp6\njs.h:89,
                 from C:\Users\Robert\Desktop\test-njs\.nectar\umnp6\async.cpp:37:
C:\Users\Robert\Desktop\test-njs\.nectar\umnp6\event.h: In function 'void NJS::Event::sleep(uint64_t)':     
C:\Users\Robert\Desktop\test-njs\.nectar\umnp6\event.h:26:9: error: 'std::this_thread' has not been declared
   26 |    std::this_thread::sleep_for(std::chrono::milliseconds(_timer));
      |         ^~~~~~~~~~~
[!] Compilation error
```
Is any requirement or dependency missing or it's me 🤔?

**Comment by adrien-thierry** [comment]
Hi, fine and you ?

What is your os and environment ?

**Comment by InDIOS** [comment]
I'm good thanks, i'm running `Windows 10 1904.572`, `GCC (MinGW GCC Build-2) 9.2.0` and `NodeJS 14.11.0`

**Comment by adrien-thierry** [comment]
You need MinGW with POSIX thread

**Comment by InDIOS** [comment]
Solved, I've followed a VSCode Cpp documentation and i moved from MinGW to MinGW64 and all is alright. Thank's for the quick answers.
