### ISSUE TITLE
Compilation error returning anonymous function

### ISSUE THREAD

**Issue by InDIOS** [NectarJS/nectarjs#114]
Hi @adrien-thierry. Testing some code, like always 😂, i found that when you have this code:
```js
function some() {
  return function () { // This never compile to a lambda expression in c++
    // do something ...
  }
}
```

Maybe `createAnon` function isn't working properly.
Greetings.

**Comment by adrien-thierry** [comment]
Thx for the issue, 

I will add a visitor for returning a lambda

**Comment by adrien-thierry** [comment]
Sorry for the delay to address this issue, i was working on performance, i will correct this one this week
