### ISSUE TITLE
Error compiling http example

### ISSUE THREAD

**Issue by bil-ash** [NectarJS/nectarjs#116]
I compiled some of the other examples and they compiled properly. But the [http](https://github.com/NectarJS/nectarjs/blob/master/example/http.js) example does not compile. The js to c++ conversion works fine but the c++ compilation gives error. I have tried both on Ubuntu 18.04(g++ 7.5.0) and Windows(MingW) and error occurs on both.Please check if it compiles with the latest version of nectarjs on your computer.

**Comment by adrien-thierry** [comment]
Hi @bil-ash ,

Thank you for reporting the issue, we just finished a big refactoring that impacted the http example, i will update it soon,

Thx

**Comment by bil-ash** [comment]
Please fix the http example before adding new features (like thread)

**Comment by adrien-thierry** [comment]
Hi @bil-ash ,

Corrected in 3e7aa75 and v0.7.94, give me your feedback.

I will update this module soon to make it more performant

**Comment by bil-ash** [comment]
Even with the latest version of nectarjs, I am getting cpmpilation errors on both Ubuntu and Windows.Attaching underneath the error log on Ubuntu-
`In file included from /mnt/d/spc/njs/.nectar/1bpyl/lib/njs-http.h:28:0,
                 from /mnt/d/spc/njs/.nectar/1bpyl/srv.cpp:49:
/mnt/d/spc/njs/.nectar/1bpyl/lib/httplib.h: In function ‘std::__cxx11::string httplib::detail::if2ip(const string&)’:
/mnt/d/spc/njs/.nectar/1bpyl/lib/httplib.h:2079:38: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
     if (ifa->ifa_addr && ifn == ifa->ifa_name) {
                                      ^~~~~~~~
In file included from /usr/include/c++/7/string:52:0,
                 from /mnt/d/spc/njs/.nectar/1bpyl/srv.cpp:24:
/usr/include/c++/7/bits/basic_string.h:6043:5: note: candidate 1: bool std::operator==(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
     operator==(const basic_string<_CharT, _Traits, _Alloc>& __lhs,
     ^~~~~~~~
In file included from /mnt/d/spc/njs/.nectar/1bpyl/njs.h:96:0,
                 from /mnt/d/spc/njs/.nectar/1bpyl/srv.cpp:37:
/mnt/d/spc/njs/.nectar/1bpyl/operator.h:517:10: note: candidate 2: NJS::VAR operator==(NJS::VAR, T) [with T = char*]
 NJS::VAR operator== (NJS::VAR _left, T right)`

The log for error on Windows is very long so I am not attaching here.

**Comment by adrien-thierry** [comment]
thank you for your feedback,

what is your gcc/clang version ?

**Comment by bil-ash** [comment]
As mentioned in the first comment of the issue,g++7.5.0

**Comment by adrien-thierry** [comment]
Could you try with gcc9 or gcc10 ?

**Comment by bil-ash** [comment]
I will see if it is possible to update gcc on my side. I shall inform you by tomorrow

**Comment by adrien-thierry** [comment]
For Windows you can find ready to use binaries here: http://winlibs.com/

**Comment by adrien-thierry** [comment]
I try on linux with gcc7, this is just a warning, compilation is fine

you can try to directly run the compiled file with `--run` flag

**Comment by bil-ash** [comment]
I am extremely sorry,I did not notice that on Ubuntu the executable was generated. Actually I first tried on Windows where it did not compile(most probably due to old MinGW).Then I tried on Ubuntu,but did not notice that the log was for warning and not error and also that the executable was actually generated.
Since the issue has been resolved,I am closing it.
