### ISSUE TITLE
I can't compile hello world

### ISSUE THREAD

**Issue by usercybe** [NectarJS/nectarjs#121]
hello, I use a windows machine and I tried to compile a simple hello world program with this code:
```
console.log("hello, world");
```
it gave me lots of errors and I don't understand a single word from it. here is a picture of the errors on the terminal [https://usercybe.is-a.fail/9ng431](url)

**Comment by usercybe** [comment]
please help asap

**Comment by adrien-thierry** [comment]
Hi @usercybe ,

Which version of g++/clang++ did you install ?

**Comment by usercybe** [comment]
@adrien-thierry 6.3.0

**Comment by adrien-thierry** [comment]
Download GCC10 and put it in your path: https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r3.zip

**Comment by usercybe** [comment]
@adrien-thierry thanks! solved it. I'm closing the issue.

**Comment by usercybe** [comment]
@adrien-thierry , g++ works now but it says ```g++: fatal error: cannot execute 'cc1plus': CreateProcess: No such file or directory```

**Comment by adrien-thierry** [comment]
Which env do you try to compile ? What is your command ?

**Comment by usercybe** [comment]
@adrien-thierry nectar hello.js
all I did was this

**Comment by usercybe** [comment]
```[*] Generating source file
[*] Compiling with preset: speed
g++: fatal error: cannot execute 'cc1plus': CreateProcess: No such file or directory
compilation terminated.
[!] Compilation error```I extracted the file directly into the mingw which I have a path env there

**Comment by adrien-thierry** [comment]
you need all the files inside the zip, not just g++

**Comment by usercybe** [comment]
@adrien-thierry do I have to extract it into the whole mingw?

**Comment by usercybe** [comment]
thanks! actually that was what I was supposed to do.
