### ISSUE TITLE
Question on License - Output files License issue

### ISSUE THREAD

**Issue by NathanaelA** [NectarJS/nectarjs#123]
I see the license was changed to GPL 3, however I can see a issue with this.   Maybe it is intentional, but hopefully it was unintended?

When using NectarJS, because you are linking in the Nectar libraries code (which is included in this repo under the same GPL 
 license) this would currently cause all projects from anybody wanting to use/compile with NectarJS to now be required to be under GPL.

If you are unaware GCC is also under GPL 3, but they have an extra clause called the Runtime Library Exception; to make it clear that any resulting code including code linked with the underlying GPL runtimes can be put under any license that the user wants.   (Link: https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html )  -- Any actual source changes to GCC or LibStdC remain GPL; but my code (and the resulting runnable executable) linked into a native/compiled application can be under whatever license (including MIT, Apache, non-free, etc) I desire.

Can we either change the licensing to Apache or MIT, or add the extra  `Runtime Library Exception` clause to your current GPL 3 license?

**Comment by adrien-thierry** [comment]
Hi @NathanaelA ,

thank you for the info, I will update it

**Comment by adrien-thierry** [comment]
@NathanaelA https://github.com/nectar-lang/NectarCPP/blob/main/RUNTIME-EXCEPTION

**Comment by NathanaelA** [comment]
@adrien-thierry - AWESOME Thanks!!!  :100:    
I think you will  also need to add this to this repo; as the JS code you have in this repo is also linked in if I am reading the build process code correctly.

**Comment by adrien-thierry** [comment]
Hi @NathanaelA , 

Updated with 0d366c9 and fe329dc

**Comment by NathanaelA** [comment]
Awesome.  Thank you very much!    :100: :dancers:      I think the reason I didn't see it is it wasn't in the base folder, you might consider either adding it to the actual LICENSE file or creating a copy of the exception license it in the root folder, as right now people coming here will see only GPL and might just move on...      But this issue is complete...  :D
