### ISSUE TITLE
basic compiling doesnt work

### ISSUE THREAD

**Issue by KCGD** [NectarJS/nectarjs#126]
I tried making a basic hello world program but it threw a tsunami of compiler errors at me
the code is just `console.log("hello world")` and i ran the command `nectar hello.js -o hello.exe`

i could provide the output of the compiler if you need

**Comment by adrien-thierry** [comment]
Hi @KCGD ,

What is your environment ? What is your version of GCC/CLang ?

**Comment by KCGD** [comment]
@adrien-thierry 
im using node v10.16.0
npm 6.14.9
NectarJS v0.7.155
GCC (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0

on windows 10 x64 version 10.0.18363 version 18363

**Comment by adrien-thierry** [comment]
try with an higher version of GCC (with c++ 17 support)

**Comment by KCGD** [comment]
@adrien-thierry, i upgraded to g++ 10.2.0, still gives me the same error.
is that the right g++ version?
also does the node version matter?

**Comment by adrien-thierry** [comment]
Yes, it should be good,

What is the error log ?

thx

**Comment by KCGD** [comment]
@adrien-thierry it just worked, apparently I declared a variable but never used it and that made the compiler freak out for whatever reason
I attached the previous error log if you want
[err.txt](https://github.com/NectarJS/nectarjs/files/6084622/err.txt)

**Comment by adrien-thierry** [comment]
Perfect thx !

I will check it

**Comment by wwderw** [comment]
I've gotten an issue like that when using C for WASM via emscripten, declaring a variable and not using it.  I think that's just part and parcel with compiling.
