### ISSUE TITLE
for loop parsing error

### ISSUE THREAD

**Issue by PassionPenguin** [NectarJS/nectarjs#127]
```
for(let i=arr.length;i--){}
```

This works on browser but in nectarjs it says 
```
[error] Parsing error: Unexpected token ) line 3 column 25 in file tmp.js
```

**Comment by VigneshMurugan** [comment]
@PassionPenguin Not sure if the for loop syntax which have used is right. `for(let i=arr.length;;i--){}`  worked for me

**Comment by adrien-thierry** [comment]
@PassionPenguin is this syntax es5/6 ?

@VigneshMurugan thx for this info

**Comment by PassionPenguin** [comment]
while it seems to be my prob, but dont know why i did successfully run that code yesterday on chrome but now it fails
