### ISSUE TITLE
Meta: Collaborate With AssemblyScript

### ISSUE THREAD

**Issue by sirinath** [NectarJS/nectarjs#129]
Since this project has some commonality with AssemblyScript there is possibility to collaborate. This is just and idea to explore.

**Comment by obnoxiousnerd** [comment]
NectarJS also aims to preserve the dynamicity of JavaScript whereas AssemblyScript is a strict, typed subset of JS( or TS). And AssemblyScript focuses on WASM while NectarJS focuses on cross-platform binary generation. So what ideas do you have when you say collaboration?

**Comment by sirinath** [comment]
NectarJS  back end may be a super set of the AS or TS backend. So there might be shared parts.

**Comment by obnoxiousnerd** [comment]
NectarJS transpiles JS to C++ code which is then passed to `gcc` or any other compiler of choice to generate the end file, whearas AssemblyScript uses `binaryen` to directly compile to WASM. So based on this inital observation, there is little room for collaboration until a custom transpiler for WASM is built. So let us hear from @adrien-thierry.

**Comment by adrien-thierry** [comment]
As @obnoxiousnerd  said, the objective of AssemblyScript is to transpile/compile a subset of TS to WASM. On way could be that AS uses NectarCPP ( https://github.com/Nectar-lang/nectarcpp ) and transpile to c++ before compiling, but i don't see any interest compared to what they are doing... If there is any other idea, it could be interesting

**Comment by sirinath** [comment]
Perhaps:
1. nectar-lang can use MIT instead of *GPL.
2. Integration to front ends for TS, PS, CS, Elm, etc. use their compiler to transpile to JS and Nectar takes over.

**Comment by obnoxiousnerd** [comment]
@sirinath Your second point is already in the works. We have TypeScript integration done, with more coming soon(I'm thinking of working on some). Although I can't comment much on changing license of NectarCPP but I think its a good move, considering the main transpiler, NectarJS is now under MIT.

**Comment by adrien-thierry** [comment]
Hi, a big update will be released soon, with a lot of new stuff, better JS support (prototypes), better perf, and a lot of new features (low level binding, operator overloading ...)
