### ISSUE TITLE
Custom Wasm imports

### ISSUE THREAD

**Issue by willemneal** [NectarJS/nectarjs#131]
Currently when compiling to Wasm, I get the following imports generated:

```
i _embind_register_function
i emscripten_run_script
i _embind_register_void
i _embind_register_bool
i _embind_register_std_string
i _embind_register_std_wstring
i _embind_register_emval
i _embind_register_integer
i _embind_register_float
i _embind_register_memory_view
i fd_seek
i fd_close
i fd_write
i emscripten_thread_sleep
i environ_sizes_get
i environ_get
i fd_read
i proc_exit
i args_sizes_get
i args_get
i clock_time_get
```

Is there anyway to specify the imports?

**Comment by adrien-thierry** [comment]
Hi @willemneal 

yes, what do you want to import for example ?

**Comment by willemneal** [comment]
Specifically here: https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/environment/blockchain_interface.rs#L5
Which is the same as: https://github.com/near/near-sdk-as/blob/master/sdk-core/assembly/env/env.ts

All exported functions take no arguments and access the arguments through deserializing a blob of bytes from the host functions above.

**Comment by adrien-thierry** [comment]
we can add them in a module for the wasm env, we can try with one to check if it's working good and then add the others

**Comment by willemneal** [comment]
@adrien-thierry Sounds good.  So just to be clear, it's possible to just have a single imported function. Say:

```
  export declare function log_utf16(len: u64, ptr: u64): void;
```

Without any others required by emscripten?

**Comment by adrien-thierry** [comment]
I think i understand better your question : you don't want to have some emscripten imports and just have the one you decide ?

**Comment by willemneal** [comment]
Yeah exactly have all the needed C/C++ stuff completely contained in the binary with only my imports and exports that take no arguments.

**Comment by adrien-thierry** [comment]
Hi @willemneal , by default now all modules are unloaded, so it means that you can have only the import you need

**Comment by willemneal** [comment]
@adrien-thierry That's great! Any examples? I couldn't find it at a glance.

**Comment by adrien-thierry** [comment]
The update is coming really soon with some examples: the default compilation env will have no import, but by specifying `--env js` it will import default JS modules (console, Math etc)
So for WASM, no module will be loaded
