### ISSUE TITLE
Unterminated string constant line 13794 column 17

### ISSUE THREAD

**Issue by jcubic** [NectarJS/nectarjs#132]
I have no idea what is line 13794, according to nectarjs, because it's the first line of this function:
```javascript
    function balanced(code) {
      var maching_pairs = {
        '[': ']',
        '(': ')'
      };
      var tokens;
```

The code is transpiled using Babel. It's a Scheme interpreter written in JavaScript.

**Comment by adrien-thierry** [comment]
Corrected in the next version (we wrote our own parser and we're not using regexp anymore to parse code)
