### ISSUE TITLE
Documentation: Compatibility Table

### ISSUE THREAD

**Issue by fernandosantucci** [NectarJS/nectarjs#14]
In order to avoid constant complaints about implementations not yet supported, it would be important to create a compatibility table, such as ECMAscript (link below), placed prominently in the product documentation.

[https://kangax.github.io/compat-table/es6/](https://kangax.github.io/compat-table/es6/)

**Comment by adrien-thierry** [comment]
See https://github.com/NectarJS/nectarscript
