### ISSUE TITLE
nectarjs.com down

### ISSUE THREAD

**Issue by JoLoZ** [NectarJS/nectarjs#140]
The title pretty much says it all. nectarjs.com is [unreachable](https://www.isitdownrightnow.com/nectarjs.com.html).

Hope I could help!

**Comment by adrien-thierry** [comment]
Thank you, it's an ovh dns/redirection problem, i will check it

**Comment by adrien-thierry** [comment]
I solved it, thx

**Comment by paulocoghi** [comment]
Down again.

**Comment by adrien-thierry** [comment]
Hi @paulocoghi , nectarjs.com is down ?

**Comment by paulocoghi** [comment]
I found the issue: when accessing it with `https`, the redirect doesn't occur.

**Comment by adrien-thierry** [comment]
Thank you, it's seem it's a problem in the ovh side, they don't manage a https redirection, only http, i will check

**Comment by Erudition** [comment]
Https redirect still down for me.

**Comment by adrien-thierry** [comment]
Yes, OVH has a big problem with that, i will solve it
