### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by spillz-dxb** [NectarJS/nectarjs#141]
Hi,
Is there support for ESP32 devices yet.
Thanks

**Comment by adrien-thierry** [comment]
Hi, yes there is

**Comment by spillz-dxb** [comment]
Fantastic , how is the target passed as are there any examples i can follow , also i am using some node.js modules with dependencies , appreciate any tips/directions

**Comment by adrien-thierry** [comment]
I will try to update the doc soon, we already made some tests on our esp32 boards but i didn't update the doc yet
