### ISSUE TITLE
Parsing Error: Unexpected Token

### ISSUE THREAD

**Issue by thiago-coucello** [NectarJS/nectarjs#142]
I got this error while trying to build with nectar:

`$ nectar ./src/index.js
[*] Generating source file
[!] Warning : index file of module path seems empty
[!] Warning : index file of module dotenv seems empty
[warning] 'fs' is assigned a value but never used. line 1 column 7 in file src\administrador.js
[error] Parsing error: Unexpected token => line 57 column 27 in file firebase\firebase.js
error Command failed with exit code 1.`

it refers to this part off my code:

`const BancoEmp = async () => {`

**Comment by adrien-thierry** [comment]
Hi @thiago-coucello , NectarJS does not support all the npm/node modules yet
