### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by czkoko** [NectarJS/nectarjs#144]
After a simple trial, I found this is a great project, which can even change the future of javascript, but there is still a lot of work to be done.Need to promote this project so that more developers can understand it and join the project to complete it together.
Hope to see its completed version as soon as possible.

**Comment by adrien-thierry** [comment]
Hi @czkoko , thank you very much for your support ! Yes, there is a lot of work to be done, but still NectarJS is an interesting project. Don't hesitate to join us and on Discord and tell us how you could help
