### ISSUE TITLE
nectarjs.com is down again

### ISSUE THREAD

**Issue by rrjanbiah** [NectarJS/nectarjs#148]
[nectarjs.com](https://nectarjs.com/) linked in GitHub is down again. https://nectar.js.org/ is up though, but that doesn't have much information; especially missing the pages linked in GitHub

**Comment by adrien-thierry** [comment]
Hi @rrjanbiah , same as #140 , OVH has a some problem, it's the https redirection that does not work, i'll find a solution

**Comment by rrjanbiah** [comment]
Sure, if you own https://nectar.js.org/, please adjust the contents there too

**Comment by adrien-thierry** [comment]
The content of this site is open source, you can find it here: https://github.com/NectarJS/nectar.js.org
