### ISSUE TITLE
Integer overflow and crash

### ISSUE THREAD

**Issue by NoCheroot** [NectarJS/nectarjs#15]
I have two issues when compiling this with NectarJS and running it:

```javascript
var x = 2147483647;
var y = 2147483648;

console.log(x);
console.log(y);
console.log(x+1);
```

I get the following output and a crash:

![image](https://user-images.githubusercontent.com/10468415/34650838-05dcadf6-f38d-11e7-93f0-5e516be1c5cd.png)

In other javascript engines

```javascript
var y = 2147483648;
console.log(y);
```

outputs 2147483648

![image](https://user-images.githubusercontent.com/10468415/34650893-e4ac199a-f38d-11e7-8442-d7f1428be1f8.png)

![image](https://user-images.githubusercontent.com/10468415/34652292-fced66da-f3a1-11e7-8db5-39ac6d651e21.png)

NectarJS, unless I'm reading this wrong, appears to store 2147483648 in a local variable as a 32 bit int (mov dword [rsp + 0x80], 0x80000000)

![image](https://user-images.githubusercontent.com/10468415/34650971-54aa8ed8-f38f-11e7-84d0-77b9db0b9da9.png)

then outputs it later with fprintf using %ld.

![image](https://user-images.githubusercontent.com/10468415/34652489-799c31f0-f3a4-11e7-914b-840dff99db5c.png)

When I compile this with MinGW:

```c
#include <stdio.h>

int main () {
    int y = 2147483648;
    fprintf(stdout,"%ld\n%lu\n", y, y);
    return 0;
}
```
2147483648 is stored the same way (mov dword [local_4h], 0x80000000).

![image](https://user-images.githubusercontent.com/10468415/34652272-9cf4cca0-f3a1-11e7-9016-1d9aff01f95d.png)

%ld has the same output as NectarJS, and %lu has the expected output.

![image](https://user-images.githubusercontent.com/10468415/34652196-c66ee756-f3a0-11e7-8f66-7ba6069deaff.png)

Is this a matter of NectarJS incorrectly choosing %ld for fprintf in this case, or a big number support problem in general?

The crash is caused here (remember 2147483647 is sitting in local variable rsp + 0x60):

![image](https://user-images.githubusercontent.com/10468415/34651521-e9764dd4-f396-11e7-9679-282c3d103161.png)

![image](https://user-images.githubusercontent.com/10468415/34651538-191a2aa6-f397-11e7-94c5-6b7d80223e39.png)

![image](https://user-images.githubusercontent.com/10468415/34651958-7e8cf0ca-f39d-11e7-8a1b-bc14e4868edf.png)

It looks like strlen is called on 2147483647 (0x7fffffff) and somehow results in strlen treating 0x7fffffff as an address.  I don't understand why this happens yet, and I have not reproduced it in c or assembly so far.  Bug?

**Comment by adrien-thierry** [comment]
Thx, added to the roadmap, currently we don't manage big int / double / float, we focusing on int/string/array/object/mixed

We are thinking about the best way to manage Numbers 
( cf https://github.com/josdejong/mathjs/ http://2ality.com/2012/04/number-encoding.html )
