### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Sacha-Bombard** [NectarJS/nectarjs#150]
Hi ✋🏻,

I've got this error compile and I don't understand what is the problem with line 24. 

**main.js (line 24)**
```javascript
app.use(express.static(path.join(__dirname, "public")));
```

I tried with this version (still doesn't worked)
```
app.use(express.static("public"));
```

Thanks 👍🏻

**Comment by adrien-thierry** [comment]
Hi !

Sadly NectarJS does not support express for now

**Comment by Sacha-Bombard** [comment]
Hi !

Thank you for the info 😄
