### ISSUE TITLE
Update description project URL

### ISSUE THREAD

**Issue by OitoH** [NectarJS/nectarjs#152]
URL changed from https://nectarjs.com to https://nectar.js.org/

**Comment by adrien-thierry** [comment]
Hi ! thx, we will update everything really soon, a lot of big news are coming

**Comment by Erudition** [comment]
![image](https://github.com/NerdLang/nerd/assets/3915447/d5ac192f-b443-48bd-bf92-d2b10d2b5020)
Hasn't changed?

**Comment by adrien-thierry** [comment]
i need to make another website, if someone wants to help me he's welcome
