### ISSUE TITLE
Dead link to register for an ID?

### ISSUE THREAD

**Issue by forcie** [NectarJS/nectarjs#23]
I'm confused as to how registering for an ID:
```
> sudo nectar --single hello.js
[!] Unkown id, please register on https://nectarjs.com and add your id in your client.
```
![image](https://user-images.githubusercontent.com/1842198/36738804-bbf5c0b8-1bde-11e8-9576-3af330cdd87c.png)

**Comment by adrien-thierry** [comment]
Corrected, it was an hosting problem (ssl not enabled on nectarjs.com)
