### ISSUE TITLE
(Enhancement) >>> Not Implemented

### ISSUE THREAD

**Issue by MrSonicMaster** [NectarJS/nectarjs#25]
When I try to compile my project, I receive the message

```Expression : >>> - Not Implemented Yet in BinaryExpression```

This is necessary for basically all uses I have for this, hopefully it can be implemented soon, or if someone could present a workaround to me that would be great. Until then, I'll be looking on my own for a workaround. Thanks!

**Comment by adrien-thierry** [comment]
It's implemented now, we are testing it before release.

**Comment by MrSonicMaster** [comment]
Sounds great! Thank you. Hopefully the update works out great and will be pushed to the public soon.
