### ISSUE TITLE
Locale or Private Server Compiling

### ISSUE THREAD

**Issue by OrangeDrangon** [NectarJS/nectarjs#28]
In the future will it be possible to compile either locally or on vps of some sort.

**Comment by adrien-thierry** [comment]
You will be able to use community edition on your own server/computer

**Comment by adrien-thierry** [comment]
core/nativejs, the local compile code, is now available on the main repo

**Comment by mhf-ir** [comment]
Any documentation about private compiling ?

**Comment by adrien-thierry** [comment]
It's coming, 

For starting, you need gcc/g++, and pass thecompiler to nectarjs in the cli

ie for g++: ./nectar.js --compiler g++ example/string.js
for g++-8:   ./nectar.js --compiler g++-8 example/string.js

**Comment by mhf-ir** [comment]
```
sweb@sweb-laptop:/tmp/aaa/nectarjs$ ./nectar.js --compiler g++ example/string.js
'[!] Please set your id and your key before build (see nectar --help)'
```
Why do i need id and key?

After set id and key as random string.

Why do i need eslint ?
```
./nectar.js --compiler g++ 1.js 
/bin/sh: 1: eslint: not found
NectarJS: Compilation Error : 


child_process.js:656
    throw err;
    ^

Error: Command failed: cd /tmp/aaa/nectarjs/core/nativejs && ./njs /tmp/aaa/nectarjs/1.js --compiler g++ -o /tmp/aaa/nectarjs/1-linux-x86-64.bin
/bin/sh: 1: eslint: not found
NectarJS: Compilation Error : 



    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at /tmp/aaa/nectarjs/nectar.js:635:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

after install eslint as dependency package. not work.
But after global package it's done.

I think these parts must be as documentation as well.

Thanks.

**Comment by adrien-thierry** [comment]
Right,

You're using the NPM version, outdate now, the github repo embed the native compiler, so it doesn't force cloud compilation
