### ISSUE TITLE
Let, const, promises, async, await, and arrow syntax

### ISSUE THREAD

**Issue by OrangeDrangon** [NectarJS/nectarjs#29]
Planned not planned what is the plan on following emcascript

**Comment by adrien-thierry** [comment]
It's planned,

NectarJS will follow as much as possible EcmaScript

**Comment by lezsakdomi** [comment]
In short it's a duplicate of #4

**Comment by Saiv46** [comment]
It's using babel or anything to transpile ES6+ code for now?
