### ISSUE TITLE
https://nectar-lang.com broken / timeout

### ISSUE THREAD

**Issue by sfcgeorge** [NectarJS/nectarjs#32]
For a couple days now it seems to do nothing then webcompile eventually times out with 504.

**Comment by adrien-thierry** [comment]
Hi,

thx for your feedback,

for wich platform does it fail ?

Just try on linux-x86-64, works great

14/09/2018 à 23:05:02 -> [+] Compilation successful
[*] Tips : on Linux, don't forget to : 'chmod +x result-linux-x86-64.bin'.

**Comment by sfcgeorge** [comment]
Right, it doesn't work for Mac OS X, which is the default for the dropdown so I assumed it didn't work at all.

**Comment by adrien-thierry** [comment]
Corrected, router error

**Comment by sfcgeorge** [comment]
Thanks, works great now.
