### ISSUE TITLE
Unexpected Compilation Error with simple JSON function

### ISSUE THREAD

**Issue by markmelville** [NectarJS/nectarjs#33]
This is my JS file, which results in "Unexpected Compilation Error":
```
function json_parse(json)
{
  return JSON.parse(json);
}
console.log(json_parse("{}"));
```
The only difference between this and a version that compiles is the introduction of the `JSON` object. Isn't that a built-in javascript object? Should this be expected to work?

**Comment by adrien-thierry** [comment]
Thank your for your feedback,

We haven't integrate JSON object in NectarJS yet,

We will soon, and it will be open source in NectarJS modules repos

**Comment by markmelville** [comment]
Could an explanation be given about why this was closed? Is this feature no longer on the roadmap? Or was it implemented?

**Comment by adrien-thierry** [comment]
We are modifying algorithms and prioritizes, right now we are generating bytecode, so no more JSON problems

We also embedded our own framework in NectarJS for rapid application development and deployment

We are focusing on something that is working first , we good functionalities, and after we will continue the low level compilation part
