### ISSUE TITLE
[!] Unexpected network error

### ISSUE THREAD

**Issue by sfcgeorge** [NectarJS/nectarjs#34]
The short example code snippets work fine but on longer code I get `[!] Unexpected network error`. Perhaps there is a maximum length you support, or maybe the code is too complex.

Out of curiosity for whether it would work I used the Opal Ruby to JavaScript transpiler to transpile a short snippet of Ruby code which ends up being much longer JS code, but still a single ES5 file. Then I tried running that through Nectar.

`nectar --target mac-osx hello.js --single`

[hello.js.zip](https://github.com/NectarJS/nectarjs/files/2392290/hello.js.zip)

**Comment by adrien-thierry** [comment]
We are working on python and ruby transpilation + compilation with NectarJS

I'll look  soon on code size and erros
