### ISSUE TITLE
Unexpected network error

### ISSUE THREAD

**Issue by mordeccai** [NectarJS/nectarjs#35]
[](url)
<img width="255" alt="nectorerror" src="https://user-images.githubusercontent.com/18606080/45806150-000b7780-bcc9-11e8-8a02-e6da6aee0560.PNG">

I am unable to compile the examples provided using the `--example` flag

**Comment by mordeccai** [comment]
I have a strong internet connection. So that cannot be an internet issue

**Comment by adrien-thierry** [comment]
Hi,

Are you behind a firewall or a proxy ?

**Comment by adrien-thierry** [comment]
Did you install NectarJS with snapd or npm ?

**Comment by mordeccai** [comment]
I used npm

**Comment by mordeccai** [comment]
I am not sure. I am using windows. The command used to work before. This
started happening when i lost my internet connection.

**Comment by adrien-thierry** [comment]
Are you able ton ping api.nectarjs.com ?

**Comment by mordeccai** [comment]
[image: image.png]

**Comment by adrien-thierry** [comment]
You have not uploaded the image

**Comment by dguayrobotiq** [comment]
@adrien-thierry Having this issue as well trying to bundle my app. Pinging `api.nectarjs.com` doesn't seem to work as well...

**Comment by jakephot** [comment]
Hello. I just found this project and it looks promising. But I am experiencing the same error...

```
$ nectar --verbose hello.js
[!] Unexpected network error
```

`hello.js`
```
console.log('Hello there!');
```

I cannot `ping api.nectarjs.com`  either. It returns an error like `Request timeout for icmp_seq 0`. I also have a decent connection and am not experiencing troubles accessing other websites. I am not using firewall or proxy. I am on MacOX Mojave and used npm to install nectar is that matters.

**Comment by adrien-thierry** [comment]
jakephot, can you access http://nectar-lang.com ?

**Comment by jakephot** [comment]
Yes I can, but compiling on the console fails:
![screen shot 2019-02-13 at 11 33 47 pm](https://user-images.githubusercontent.com/8734187/52723114-e35d3c80-2fe7-11e9-855b-6c12eb0335fa.png)

**Comment by adrien-thierry** [comment]
Yes, i'm updating the Mac server, it will be online soon

others targets are working

**Comment by adrien-thierry** [comment]
Now it's working, could you test it again ?

**Comment by jakephot** [comment]
Thank you for the update. Now I was able to created a binary file and it is working :)

```
$ nectar --verbose hello.js
[+] Compilation done

$ ./hello-mac-osx.bin
Hello there!
```

I will go through the tutorial and find what I can do with nectar.

**Comment by praveenkanike** [comment]
Hi Team,
The issue is still persisting.
