### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by ofarukcaki** [NectarJS/nectarjs#37]
I'm getting this error when I want to compile my javascript. It happened after I added **xml2js** npm package

```λ nectar.cmd index.js
fs.js:119
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)```

**Comment by viane** [comment]
same here

**Comment by adrien-thierry** [comment]
What command did you use ?

**Comment by werlious** [comment]
same issue here, however i have no idea what could be causing it as im integrating into an existing application. however, the only time i read from a directory (checked many times now) is when i explicitly call fs.readdir. every other fs call i make is only to files, using fs.readFile. im assuming it has simething to do with the async file calls i make, but am really hesitant to go changing everything over to sync. Any Suggestions? ill be looking into this in the mean time, but if anyone want to put heads together on it let me know

**Comment by hrushka** [comment]
Getting the same thing. `nectar server.js` using a very simple hello world with `terminal-kit` module.

**Comment by jasir** [comment]
Same here...

**Comment by adrien-thierry** [comment]
Seems to come from yarn install

**Comment by LubomirJagos** [comment]
I get to this error, but it was because I was run command "nectar --target win-x86-32 string.js" in the same directory where I had copy of nectarjs directory.
So if you got something like this try to copy your .js file to separate directory and compile it within it.
That was my fault, which cost like 2hrs :D ...but now I know how NectarJS is working inside :D

**Comment by adrien-thierry** [comment]
Great @LubomirJagos ! Thank you for your feedback

**Comment by geocine** [comment]
I am not running this on the nectarjs directory however I get the same error

```
fs.js:115
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:491:3)
    at tryReadSync (fs.js:330:20)
    at Object.readFileSync (fs.js:367:19)
    at /Users/geo/.nvm/versions/node/v10.14.1/lib/node_modules/nectarjs/extern/adm-zip/adm-zip.js:273:38
    at Array.forEach (<anonymous>)
    at Object.addLocalFolder (/Users/geo/.nvm/versions/node/v10.14.1/lib/node_modules/nectarjs/extern/adm-zip/adm-zip.js:269:12)
    at /Users/aivan/.nvm/versions/node/v10.14.1/lib/node_modules/nectarjs/nectar.js:499:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

I am trying this command for the example file

```
nectar example.js
```

**Comment by geocine** [comment]
I resolved my issue, it was trying to include the `.sonarlint` that I have in my current directory. I deleted that dot folder and it worked.

Should probably add an option to be able to exclude directories or just exclude dot folders completely.

**Comment by adrien-thierry** [comment]
Great, don't hesitate to help me by making a pull request
