### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by trusktr** [NectarJS/nectarjs#39]
Can we write WebGL apps with Nectar? I guess it needs JS glue with WebAssembly. Any plans?

**Comment by adrien-thierry** [comment]
We'll be able to write WebGL apps with Nectar,

I'm reorganizing the project

**Comment by PhilT** [comment]
This would be amazing!

Do you or will you be supporting other Browser APIs as well?

**Comment by adrien-thierry** [comment]
Yes sure,

The aim is to globally support JS/ES, but I need help ( :

**Comment by PhilT** [comment]
I'm not sure I'm low-level enough to be able help and I certainly don't have the time right now but in about 3 months I should have a lot more time so may be able to lend a hand depending on what you need.
