### ISSUE TITLE
Not ES6 Suport

### ISSUE THREAD

**Issue by lucasrocha7111** [NectarJS/nectarjs#4]
Hello.
I receive "_Compilation error_" when I use **let**, **async**, **await** and others ES6 features.

Have some prediction to add suport for that?
Will be good specify this issue on readme?

Thanks.

**Comment by adrien-thierry** [comment]
Hello Lucas,

we are working on it (ES6 + doc + readme),

regards

**Comment by D3rise** [comment]
This issue still opened?

**Comment by adrien-thierry** [comment]
Sadly yes, I'm still alone to code
