### ISSUE TITLE
How much will it cost?

### ISSUE THREAD

**Issue by trusktr** [NectarJS/nectarjs#40]
Also what's the reason for not doing an open source model like Qt?  (they seem to be successful with their commercial licenses)

**Comment by adrien-thierry** [comment]
Yes, I'm looking at this kind of thing, I'm going to make NectarJS fully open source, so I'll need help (a lot)

**Comment by iSkore** [comment]
Do you have a set release date on the open source roll out?

**Comment by adrien-thierry** [comment]
I'm working on it, need help to clean up the code

**Comment by iSkore** [comment]
Gotcha, is there a public repo of it? Or are you doing an in-house clean up?

**Comment by adrien-thierry** [comment]
it's on a private repo right now, I could put it in this one, even if the current dev version is quite ugly

**Comment by iSkore** [comment]
That's what we are here for! Open source community help!

**Comment by adrien-thierry** [comment]
It's done, it's in core/nativejs

the core compiler tool could be used like this : ./njs --compiler g++ examples/bool.js

you need to cd in core/nativejs to test it, i'll implement it in nectarjs main script

**Comment by iSkore** [comment]
Awesome, I’ll take a look. Do you plan to keep your Compiler as a Service as the main module system or can we put that behind a flag at some point? Like —caas or something like that

**Comment by iSkore** [comment]
I think this action just closed [#28](https://github.com/NectarJS/nectarjs/issues/28)

**Comment by adrien-thierry** [comment]
We will put it as a flaag, local compilation has to be the main feature, local cross compilation with llvm is possible

**Comment by iSkore** [comment]
I figured so, sounds good.

**Comment by martinjms** [comment]
> It's done, it's in core/nativejs
> 
> the core compiler tool could be used like this : ./njs --compiler g++ examples/bool.js
> 
> you need to cd in core/nativejs to test it, i'll implement it in nectarjs main script

Hi, just found out about this project, i think you should announce this on the readme, that will definitely bring more attention to the project and people willing to help

**Comment by adrien-thierry** [comment]
thx @martinjms , good idea, done
