### ISSUE TITLE
Trying Local Compiling

### ISSUE THREAD

**Issue by OrangeDrangon** [NectarJS/nectarjs#42]
I have begun to play around with local compiling and want to begin constructing examples and the errors they result in if they do not succeed. Here is my first try:

[Code](https://github.com/OrangeDrangon/nectar-test/tree/basic-http)

The executed commands are:
```
cd node_modules/nectarjs
./nectarjs --compiler g++ ../../src/index.js
```

The error was:
![error](https://user-images.githubusercontent.com/25403517/53893123-945d6280-3ffb-11e9-8b6d-3458dc7ad2a8.png)

I tried again by removing the arrow functions and using function syntax and the error persisted in the same form.

[Arrow](https://github.com/OrangeDrangon/nectar-test/tree/b23cc7afe1ba6dd014426365a58f1f26737210a9)

[No Arrow](https://github.com/OrangeDrangon/nectar-test/tree/a064391274832c99da7e2e6ae9f75ab6b59b4737)

(Different points in GIT history)

**Comment by adrien-thierry** [comment]
Hi,

you are trying to compile a js code requiring "http" module, this module doesn't exist for now (https://github.com/nectarjs/nectar_modules)

btw, i have to remove or ask for installing eslint
