### ISSUE TITLE
Trying to get a key: An error occured, please try again

### ISSUE THREAD

**Issue by cdevienne** [NectarJS/nectarjs#43]
I would like to try nectarjs but I am unable to get a key.

Side question: why the key ?

**Comment by adrien-thierry** [comment]
Hi,

we are switching imap/smtp servers, 

you can try nectarjs with these id/key : nectop / nectop 

the key lets you use our cloud compilation platform with encryption, that's why

You can either try NectarJS localy by cloning this repos, installing g++ and eslint

**Comment by cdevienne** [comment]
Thanks!

/me eager to give it a try
