### ISSUE TITLE
Compiling JavaScript to C source code

### ISSUE THREAD

**Issue by jarble** [NectarJS/nectarjs#46]
Since NectarJS is able to compile JavaScript into WebAssembly, it may be possible to compile JavaScript into C source code using a compiler like [wasmdec](https://github.com/wwwg/wasmdec). Does NectarJS have this feature yet?

**Comment by adrien-thierry** [comment]
You can directly compile JS to c/c++ with NectarJS

**Comment by jarble** [comment]
Does the documentation explain how to compile JavaScript to C or C++?

**Comment by adrien-thierry** [comment]
Not yet, 

you have to use `njs --gen your_file.js` in the core/nativejs folder

**Comment by adrien-thierry** [comment]
There is no more core/nativejs, did you update NectarJS ?

**Comment by votecoffee** [comment]
I recently installed it.  I was looking for a transpiler to convert javascript to c++.  I'm guessing that's no longer a supported feature then?

**Comment by adrien-thierry** [comment]
Compiling to c++ is one of the main feature, so it's supported

Did you install it with npm ?

`npm i -g nectarjs`

**Comment by DuncanMacWeb** [comment]
Hi @adrien-thierry, I have installed NectarJS  globally using `npm i -g nectarjs`:

```
$ nectar --version
NectarJS v0.7.99
```

What is the correct way to generate C/C++ output from NectarJS? Many thanks!

**Comment by adrien-thierry** [comment]
Hi @DuncanMacWeb !

Thank you for your interest in NectarJS, to generate c++, use the `--generate` flag

To generate the code in a specific path, use --tmp with a path : `--tmp mypath`

**Comment by adrien-thierry** [comment]
To just compile the app, use `njs myapp.js`

**Comment by DuncanMacWeb** [comment]
Got it, thanks!
