### ISSUE TITLE
Error 'Bad Target' for 'nectar project.json'.

### ISSUE THREAD

**Issue by apoorvsingal** [NectarJS/nectarjs#48]
The command "nectar project.json" generates the error "Bad Target". I read your code and found out that this happens only in computers with arch other than the few specified in your code. For example, my pc has ARCH 'ia32' which you haven't specified in your code.

Also, if the code is not automatically able to find a target, it generates the above error (without even checking if the target in specified in project.json or not.). It should first check for target in project.json and then generate error if it is not there.

![nectar](https://user-images.githubusercontent.com/46374098/56560044-00525500-65c1-11e9-8843-1d85f0f97914.png)

**Comment by adrien-thierry** [comment]
The default target is choosen regarding your host system, so by default, if you have a x86 64 Windows system, NectarJS will choose win-x86-64 as default target
you can override the target by setting it : --target mac-osx

ia32 is the same as x86-32, i can add it to the target list
