### ISSUE TITLE
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by Marksteinsong** [NectarJS/nectarjs#51]
I did
```
necater   --verbose  a.js
```
And i run   ./a-linux-x86-64.bin

Here is the result:
```
./a-linux-x86-64.bin: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./a-linux-x86-64.bin)
./a-linux-x86-64.bin: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./a-linux-x86-64.bin)
```

I know  it's not NectarJS's  problem.But I can't fix it....... help....

**Comment by adrien-thierry** [comment]
Hi,

what is your linux os version ?

**Comment by Marksteinsong** [comment]
> Hi,
> 
> what is your linux os version ?

Centos7.2

**Comment by adrien-thierry** [comment]
Try export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
