### ISSUE TITLE
Some issues on the website

### ISSUE THREAD

**Issue by PhilT** [NectarJS/nectarjs#52]
nectarjs.com seems to stutter when scrolling on Chrome or Brave and to a lesser extent on Edge. It's like it's fighting me to scroll the page down.

Also the e in development and developers in some places has a glyph on top of it. This is incorrect.

Finally, you're loading a Google font with HTTP and this is making Brave complain about mixed content. Just need to use the HTTPS version.

This is a great idea and I look forward to seeing in progress. I'll need this in a couple of years when I want to compile my JavaScript game for distribution.

Keep it up!

**Comment by adrien-thierry** [comment]
thx for the feedback, i'll correct that
