### ISSUE TITLE
i cannot get key...

### ISSUE THREAD

**Issue by blizzardzheng** [NectarJS/nectarjs#54]
my email is candy.zhengxq@gmail.com

**Comment by adrien-thierry** [comment]
Hi, we are moving the api and trying to finance it with sponsoring

**Comment by blizzardzheng** [comment]
so how to get key right now?

**Comment by blizzardzheng** [comment]
i will do some sponsoring if it worth

**Comment by adrien-thierry** [comment]
Just take a sponsor tier at 9$ here : https://github.com/sponsors/adrien-thierry

**Comment by blizzardzheng** [comment]
@adrien-thierry done
