### ISSUE TITLE
Unexpected Compilation Error, no info

### ISSUE THREAD

**Issue by ajm2017** [NectarJS/nectarjs#55]
I'm just returning "Unexpected Compilation Error". I fixed about 500 minor syntax errors/warnings, but now this is all I see without any further description. My target seems fine. The script isn't doing anything out of the ordinary: lots of arrays, some objects, and bit functions on 32-bit ints. Any ideas?

**Comment by ajm2017** [comment]
> I'm just returning "Unexpected Compilation Error". I fixed about 500 minor syntax errors/warnings, but now this is all I see without any further description. My target seems fine. The script isn't doing anything out of the ordinary: lots of arrays, some objects, and bit functions on 32-bit ints. Any ideas?

Just FYI - I have already successfully compiled another simple test script with Nectar without any issues.

**Comment by ajm2017** [comment]
Lastly, I am on an older NodeJS 8.16 -- have to be on this comp for some legacy work. Not sure if that might cause an issue.

**Comment by adrien-thierry** [comment]
Hi, yes, all is not finished yet could share the part of your code that triggers the error ?

**Comment by ajm2017** [comment]
I have not yet deduced which part is causing it. I'll try to pare it down to see what's causing the issue.

**Comment by ajm2017** [comment]
I think I have found the offending code, but right now I'm getting the following error which I haven't seen before:  Unexpected network error

**Comment by ajm2017** [comment]
I can't confirm it yet, but I think this will cause an Unexpected Compilation Error. Seems to be the Array instantiation.

var abc = new Array(2);
abc[0] = 0; abc[1] = 1;
console.log ('hello');

**Comment by ajm2017** [comment]
I can confirm the above code will not compile in the web console: https://nectar-lang.com/
I'm still getting an Unexpected Network error now in my nodejs console.

**Comment by ajm2017** [comment]
Seems it's back up - no longer getting the network error, but at my nodejs console am still getting the Unexpected Compilation Error on the code: 

var abc = new Array(2);
abc[0] = 0; abc[1] = 1;
console.log ('hello');

Same result via the web form.

**Comment by adrien-thierry** [comment]
thank you very much

for the network error, are you behing a proxy / firewall ?

**Comment by ajm2017** [comment]
re network error - I just assumed you were updating something briefly.

**Comment by adrien-thierry** [comment]
We are launching sponsoring, we ask people to help us to maintain the API and to develop NectarJS

**Comment by ajm2017** [comment]
Cool - I'd be happy to sponsor, it's a great project. Do you think there will be support for the above soon? Or a workaround?

**Comment by adrien-thierry** [comment]
Yes, i'm sourcing people to improve NectarJS and support ES5, ES6 ...
