### ISSUE TITLE
FFI possibilities

### ISSUE THREAD

**Issue by TomasHubelbauer** [NectarJS/nectarjs#57]
Hi, I wonder if now or eventually Nectar could be used in the following way:

I defined a piece of JavaScript which depends on a platform API:

```javascript
MessageBoxW(null, 'Hello, World!', 'Hi!', 0);
```

Then I somehow defined the FFI information so that Nectar knows this function I'm invoking is a part of the platform's/target's API.

And then I compile this code using Nectar and have a binary which invokes the Windows API [`MessageBoxW`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxw).

Also, this might be a better fit for a separate issue, but anyway: I see you are providing people with keys to access Nectar while it's in alpha and also this repo doesn't include any source code. How are you going to provide Nectar when it makes out of alpha? Is it going to be open source? Free or paid?

**Comment by adrien-thierry** [comment]
Hi @TomasHubelbauer ,

We are refactoring everything, adding multi compilers cross platforms options, that's why there is no source code right now

The core src code for compilers will be open source, i will add everything in the next days

We actually use kind of FFI to be able to use existing libs, like arduino's etc

Don't hesitate to join us on Discord

**Comment by adrien-thierry** [comment]
Hi @TomasHubelbauer ,

FFI added in last push

There is a test nectar_modules with an ffi include test from cpp

**Comment by TomasHubelbauer** [comment]
Awesome, thanks for the example!

**Comment by adrien-thierry** [comment]
I updated the njs lib to don't disturb windows lib

the test module now show a message box

**Comment by TomasHubelbauer** [comment]
Even better, the current form of the example is exactly what I had in mind. :-)

**Comment by adrien-thierry** [comment]
I add a more complete example with two functions, one simple FFI function without parameters, and one other with parameter and function loading in an object
