### ISSUE TITLE
Expose more 'Compilation error' info

### ISSUE THREAD

**Issue by unlight** [NectarJS/nectarjs#6]
When I run broken JS code, I just get `Compilation error` and that's it.
Good to know:
1. What is file.
2. What is the line.
3. What is the column
4. What is the reason (why it cannot be compiled: no support or invalid syntax, or any other)
5. Stack trace

**Comment by adrien-thierry** [comment]
Added today in server side : 

`NJS:  Parse Error - Line 1: Unexpected token ILLEGAL at index: 12`

**Comment by lezsakdomi** [comment]
Please display the info at the NectarJS sandbox on the webpage too!
