### ISSUE TITLE
Key stop working and compile for arduino

### ISSUE THREAD

**Issue by glococo** [NectarJS/nectarjs#61]
Hi Adrien,

I love your project.
It will definitely short C projects by order of magnitude. Congrats.

I would like to download an example for arduino, a project.json and know how can I extend the library, like writing to the registers like pwa, adc, and so on.
When I tried to compile strings.js to different targets, it always compile for my linux no matter what I chose.

btw: my key id is ZgWZQIPcdoz
My best wishes!

**Comment by adrien-thierry** [comment]
Hi @glococo ,

thank you for your message,

I'm updating the online API with the new NectarJS vestion, could take some time,

I can you can download the arduino toolchain and use it with NectarJS to compile your project for Arduino in local, without our API,

Could you join us on Discord ?

**Comment by glococo** [comment]
ok, I joined, thanks for the Invite.
