### ISSUE TITLE
Require in comments are executed

### ISSUE THREAD

**Issue by Igorgro** [NectarJS/nectarjs#64]
If I try to compile the following code, which contain only one require inside comment:
```javascript
// require('not-exist')
```
it gives me the following error:
```
[!] Require error : not-exist
```
This means that nectar tries to execute this line despite it only contains comment.

**Comment by adrien-thierry** [comment]
Thx @Igorgro 

Yes, the genRequire function is called before i strip the code,

I will strip the comments before

**Comment by adrien-thierry** [comment]
This commit should resolve this problem: 19e6892

Could you try again ?

**Comment by adrien-thierry** [comment]
This issue is resolved
