### ISSUE TITLE
Licensing choice

### ISSUE THREAD

**Issue by MicrolemurDev** [NectarJS/nectarjs#65]
The license chosen is AGPLv3 which is non-existent and for such purposes I believe should be instead GPLv3. It is the same licensing scheme except without requirement to download the source code. This would allow it to be for example bundled with something like Debian if there was a need. So I ask for you to change the license to GPLv3.

**Comment by adrien-thierry** [comment]
Hi @MicrolemurDev ,
Does AGPLv3 disallow to bundle a package for Debian ?

Reading this, it seems not : https://lists.debian.org/debian-legal/2008/11/msg00097.html

**Comment by MicrolemurDev** [comment]
While it looks like debian may not be a problem npm packages also like to use highly permissive licenses such as MIT License. I also was going to use it in a game engine which I would hope to bundle it with it under GPLv3.

**Comment by adrien-thierry** [comment]
I will check this

**Comment by adrien-thierry** [comment]
@MicrolemurDev i'm looking Apache2 license

**Comment by MicrolemurDev** [comment]
@adrien-thierry Apache2 also works for my purpose

**Comment by sudo-carson** [comment]
Hello, any updates on a license change?

**Comment by MicrolemurDev** [comment]
Not yet. This may take quite a bit :/

**Comment by adrien-thierry** [comment]
It's coming, we are working hard on ES3 compliance, i will update it soon

**Comment by adrien-thierry** [comment]
I had a poll on Discord, don't hesitate to join us and vote

**Comment by adrien-thierry** [comment]
NectarJS is now GPLv3
