### ISSUE TITLE
Plans to support FreeBSD?

### ISSUE THREAD

**Issue by fmh-finanzberatung** [NectarJS/nectarjs#67]
Up front: thanks to anyone working and participating on this project. It's the best idea I've seen for years.

I know this doesn't really belong in the issues section and I apologize for that. But I don't know where else to ask this question:

Are there any plans to support FreeBSD or any other BSD?

**Comment by adrien-thierry** [comment]
Hi @fmh-finanzberatung ,

Thank you for this encouraging message,

Yes, I plan to support as much OS as possible, i will add FreeeBSD as soon as possible as a supported OS.

**Comment by adrien-thierry** [comment]
@fmh-finanzberatung did you try to run NectarJS on FreeBSD ?

It should work out of the box

**Comment by mkastner** [comment]
@adrien-thierry 
Sorry, I've opened up this issue with the wrong account. "fmh-finanzberatung" is an account I administer for my contracting company. So this post is from my own account.

Getting back to your question: In fact I haven't tried it. But I'll give it a shot on FreeBSD and I'll let know about the outcome.

**Comment by adrien-thierry** [comment]
@mkastner no problem

Ok, give me a feedback when you can. You need to install node and gcc to start (gcc with c++11 at least)

**Comment by adrien-thierry** [comment]
@mkastner any news ?

**Comment by mkastner** [comment]
I apologize for the delay. It did not work. Maybe it's just "beginners luck" or I made a mistake.

Here are my specifics (please let me know, if you need further details:

- OS: FreeBSD 12.1
- compiler: gcc 9.3.0

my index.js (source):

`console.log('hello world');`

Compiler output:

[out.log](https://github.com/NectarJS/nectarjs/files/4807914/out.log)

Again I apologize, for not having gotten back to you earlier.

**Comment by adrien-thierry** [comment]
Hi @mkastner , 

did you install libc++ ?

**Comment by mkastner** [comment]
In FreeBSD libc++ is part of the base system. I need to check if there are any extra flags I need to set. I'll get get back to you, when I have figured that out. It might take a few days though.

**Comment by adrien-thierry** [comment]
Ok, thank you,

you can force compiler params with --compiler flag, example:

`nectar --compiler "g++ -gcc_flag" file.js`

If you have an error, can you copy/paste it here ?

**Comment by adrien-thierry** [comment]
@mkastner any news ?

**Comment by adrien-thierry** [comment]
@mkastner no news ?

**Comment by fmh-finanzberatung** [comment]
Sorry, didn't want to let you wait. But no, I couldn't get it running on FreeBSD. It compiles on my mac out of the box.

I keep getting the above mentioned error. I don't understand why that happens, because clang 8.0.1 should be able to handle lambdas without problems.

**Comment by adrien-thierry** [comment]
Can you update nectarjs and try again ?

I corrected the error, it was a scope problem with the lambda capture in clang

**Comment by fmh-finanzberatung** [comment]
Works like a charm! Great! I'll try some more stuff. Thanks for reminding me and for this awesome project.

**Comment by adrien-thierry** [comment]
Thank you too for taking time to test NectarJS
