### ISSUE TITLE
Feature request: HTML compiler for GUIs

### ISSUE THREAD

**Issue by 34r7h** [NectarJS/nectarjs#69]
Hi, really great work here. I'm curious what kind of effort it would take to take a standard markup language, like xml or html, to compile native guis. Probably a monumental task, eh?

**Comment by adrien-thierry** [comment]
hi @34r7h , in the objective to have something working fast, there is some c++ libs we can integrate as modules, i will check it
In a near future, it could be really great for NectarJS to have its own html engine

**Comment by 34r7h** [comment]
Yea, that would be an amazing near future. What can I do to help?

**Comment by adrien-thierry** [comment]
You could try to integrate this lib as a nectar module : https://github.com/litehtml/litehtml

**Comment by 34r7h** [comment]
ok, i'll take a stab at this next week. is there a resource guide to follow for modules or should i use something like std-fs as a starting point?

**Comment by adrien-thierry** [comment]
I will update the documentation for creating modules,

Else, yes, fs-std is a good start

**Comment by 34r7h** [comment]
ok, i'll make time to jump in. will ping w qs

**Comment by adrien-thierry** [comment]
@34r7h I added the njs-http module, it could be easily integrated with a webview

Furthermore, i started the Android iPhone integration with a webview and events

**Comment by adrien-thierry** [comment]
Maybe with this webview : https://github.com/zserge/webview

**Comment by adrien-thierry** [comment]
@34r7h i made it : nectar_modules/webview
It currently works on linux, you need pkg-config, gtk+-3.0 and 
![webview](https://user-images.githubusercontent.com/11015239/83440553-a616fb00-a434-11ea-8fa3-6089c7cb074c.png)
webkit2gtk-4.0

**Comment by 34r7h** [comment]
oh haha nice one!
i had just started a skeleton for the task but really i'm out of my depth with c https://github.com/34r7h/nectarjs/tree/master/nectar_modules/njs-webview

**Comment by 34r7h** [comment]
I'm using mac, where in nectar would we add the appropriate cocoa flag? i.e. from webview.h
or is this more complicated?

//
// ====================================================================
//
// This implementation uses Cocoa WKWebView backend on macOS. It is
// written using ObjC runtime and uses WKWebView class as a browser runtime.
// You should pass "-framework Webkit" flag to the compiler.
//
// ====================================================================
//

**Comment by adrien-thierry** [comment]
In the package.json file of the module, in lib, override the pkg-config

**Comment by adrien-thierry** [comment]
I will modify lib to accept différent arguments like compiler, platform etc

**Comment by 34r7h** [comment]
ur a legend mate.

**Comment by adrien-thierry** [comment]
Thx, i will update tomorrow the lib json property

**Comment by adrien-thierry** [comment]
It's ok, you can setup libs regarding which platforms and which compilers will compile a module, check the njs-http package.json for example
```
lib:
{
   "default": "-defaultLib",
   "linux": "-linuxLib",
   "darwin": "-darwinLib",
   "win32": 
   {
      "default": "-gccWinLib",
      "cl": "/L crtLib"
   }
}
```

**Comment by marcus-sa** [comment]
There's https://github.com/nodegui/nodegui

**Comment by adrien-thierry** [comment]
Hi @34r7h , any news ?

**Comment by 34r7h** [comment]
Hey Adrien, sorry for dropping off. Briefly played and gui works as
expected. I'll come back for more testing after finishing up client gigs.

**Comment by adrien-thierry** [comment]
Ok, thank you, I close this issue
