### ISSUE TITLE
Node suport

### ISSUE THREAD

**Issue by lucasrocha7111** [NectarJS/nectarjs#7]
NectarJS Client v0.0.46
OS: Ubuntu Gnome 16.04
Node: v7.10.1

I try use node modules and doesn't work.

Example:
`var koa = require('koa')`
`var app = new koa()`

I just receive: **Compilation error**

Obs: I'm not using `--single`

**Comment by adrien-thierry** [comment]
NectarJS 0.1.0 has now "env" compilation option. node env is compiled with LibUV and is able to support NodeJS API, modules etc.
