### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by sylvainar** [NectarJS/nectarjs#72]
I don't quite understand what this project is about so I randomly clicked on your documentation, and this link seems broken:

![image](https://user-images.githubusercontent.com/9823286/82212391-c615cd00-9912-11ea-8298-e75b6780984e.png)

**Comment by adrien-thierry** [comment]
Hi @sylvainar ,
NectarJS's main objective is to compile JS into true native binaries (for windows, mac, linux) or into firmwares (for arduino or stm32 boards for example)

I will update the documentation
