### ISSUE TITLE
require error test-harness

### ISSUE THREAD

**Issue by Raynos** [NectarJS/nectarjs#74]
```js
raynos at raynos-Precision-5530  
~/projects/fake-ses on master*
$ nectar test/index.js 
[*] Generating source file
[!] Require error : ./test-harness
```
```
raynos at raynos-Precision-5530  
~/projects/fake-ses on master*
$ head test/index.js 
'use strict'

const test = require('./test-harness').test

/** @typdef {import('aws-sdk)} AWS */
```

It looks like it does not understand `require('./test-harness')` but it DOES understand `require('./test-harness.js')`

I changed it to a full relative filename and it works.

**Comment by adrien-thierry** [comment]
@Raynos ,

Thx, I will update the require function

**Comment by adrien-thierry** [comment]
I updated the require function, should be corrected

**Comment by Raynos** [comment]
Can confirm, this fixed it.

I still get the "does not support async method / function" error but this one is fixed.
