### ISSUE TITLE
How to compile all js files?

### ISSUE THREAD

**Issue by mzaini30** [NectarJS/nectarjs#78]
I have these files:

- a.js
- b.js
- c.js

How to compile all automatically with nectar?

**Comment by adrien-thierry** [comment]
Hi @mzaini30 ,

You would like to be able to do this: nectar a.js b.js c.js ?

**Comment by mzaini30** [comment]
@adrien-thierry nectar *.js

**Comment by adrien-thierry** [comment]
Good idea, it's in the todo list cfbe744

**Comment by mzaini30** [comment]
@adrien-thierry thanks
