### ISSUE TITLE
File IO?

### ISSUE THREAD

**Issue by fluffynuts** [NectarJS/nectarjs#79]
Hi

I see that support for "fs" is still on the way, so just asking out of curiosity -- is there currently any other way to do file IO?

**Comment by adrien-thierry** [comment]
Hi @fluffynuts ,
Yes, fs is not finished yet, but you can access file by adding a module with native c++ call with ffi 

You can check the example/test.js file that call windows popup for example

I will update this issue when fs is updated

**Comment by adrien-thierry** [comment]
@fluffynuts I added the fs-std module for simple fs support, it will be improved soon

see 94689cf

**Comment by raguay** [comment]
That helps, but I still can't compile my simple script:
```JavaScript
var fs = require("fs-std");   // use with nectar.js
//var fs = require("fs");     // use with node.js
var process = require("process");

var inputFile = fs.readFileSync(process.argv[2]);
var output = '{"items": [';
var first = true;
inputFile = inputFile.toString();
inputFile = inputFile.split('\n');
for(var i = 0; i < inputFile.length; i++) {
  if(inputFile[i] !== "") {
    if(!first) {
      output += ",";
    } else {
      first = false;
    }
    var subitem = {
          uid: inputFile[i],
          type: "",
          title: inputFile[i],
          subtitle: process.argv[3],
          arg: inputFile[i],
          autocomplete: inputFile[i],
          valid: true,
          icon: {
              type: "fileicon",
              path: "~/Desktop"
          }
      };
    output += JSON.stringify(subitem);
  }
}

console.log(output + "]}");
```

**Comment by adrien-thierry** [comment]
@raguay i will check it

**Comment by raguay** [comment]
> @raguay i will check it

Thanks. Looking forward to a solution. It'll make this a great way to build cli utilities. I've been using Haskel, but I'm constantly having issues with linked libraries.

**Comment by adrien-thierry** [comment]
@raguay I added an example in the examples folder named `read_file_to_json.js`

I Updated NectarJS to make it working, should work with version v0.6.68

**Comment by raguay** [comment]
Working for me. I have the argument in the split with single quotes and it
will not compile that way. Changing to double quotes (like you had in the
examples) and it is now working. Thanks so much. This will be my main way
to do Alfred scripts going forward. Thanks!

**Comment by raguay** [comment]
I just optimized the code some more and it will compile, but not run? It looks like you can't push items onto an array? What would be the recommened way? The new code is:

```javascript
var fs = require("fs-std");
var process = require("process");

var inputFile = fs.readFileSync(process.argv[2]);
var output = {};
output.items = [];
inputFile = inputFile.toString().split("\n");
for(var i = 0; i < inputFile.length; i++) {
  if(inputFile[i] != "") {
    var subitem = {
          uid: inputFile[i],
          type: "",
          title: inputFile[i],
          subtitle: process.argv[3],
          arg: inputFile[i],
          autocomplete: inputFile[i],
          valid: true,
          icon: {
              type: "fileicon",
              path: "~/Desktop"
          }
      };
    output.items.push(subitem);
  }
}

console.log(JSON.stringify(output));
```

By doing the JSON.stringify once, I'm figuring it would save a lot of time!

**Comment by adrien-thierry** [comment]
@raguay the array.push function does not exist at the moment, I will add it

**Comment by adrien-thierry** [comment]
@raguay it should be okay, i added array.push method, could you try again ?

**Comment by raguay** [comment]
Hi,

I'm still getting errors on running:

```
»»»» ./fileToAlfred -- allcleaners.txt 'TextSoap'
                                          0|09:02:28
[!] Fatal error, object is not a function
```

I think it thinks the push function is an object. I did "npm -g update
nectarjs" to update to the latest version: 0.6.72

**Comment by raguay** [comment]
BTW: I'm having to delete the `.nectar` directory each time to clear out
old bugs.

**Comment by adrien-thierry** [comment]
@raguay : Chaining functions is not working yet, i add it to the roadmap,

You can make your script working by removing the `toString()` call on inputFile : 

`inputFile = inputFile.split("\n");`

**Comment by raguay** [comment]
Okay. Composing works, chaining doesn't work. Got it. It's working now.
Thanks.

Richard

**Comment by adrien-thierry** [comment]
@raguay function chaining is now available,
i'm correcting a bug in the object construction (subobject keys are undefined)

**Comment by adrien-thierry** [comment]
The sub object bug is corrected, your code is working good now

**Comment by raguay** [comment]
Wow. It is really working great and so fast! Thank you so much. It is also
compiling in a directory with a path that has special characters just fine.
Thanks so much for the quick fixes. My Alfred workflow is now almost
instant!

Richard

**Comment by adrien-thierry** [comment]
Did you try to compile with the `--preset speed` flag ?

**Comment by raguay** [comment]
No, I didn't know about that flag. It's very fast with the defaults. I'll
try that as well. Thanks.

**Comment by raguay** [comment]
Okay, that did seem to make it faster. Wow. Great work.
