### ISSUE TITLE
Error on use before define

### ISSUE THREAD

**Issue by romgrk** [NectarJS/nectarjs#85]
Getting `[error] 'fetchOneMessage' was used before it was defined. line 17 column 39 in file index.js`.

**Comment by adrien-thierry** [comment]
Hi @romgrk ,

Thank you for reporting an issue, what is the function `fetchOneMessage` ?

**Comment by romgrk** [comment]
Just an example, any function used before definition fails right now.

**Comment by adrien-thierry** [comment]
Yes, NectarJS force the definition before use to keep scopes and to have a predictable behabior

**Comment by romgrk** [comment]
IMHO this is incorrect. Function hoisting is a well-defined behavior of ECMAScript. It's also a very common pattern to define functions at the bottom of the file, to avoid having to read irrelevant implementation details before the main logic of the file. So unless it is implemented to keep the same behavior as in JS, NectarJS won't be compatible with non-trivial (aka without dependencies) NodeJS applications.

**Comment by adrien-thierry** [comment]
I understand,
It will ask some more work but it is possible, i will update this issue when it's done

**Comment by kitolog** [comment]
Subscribing to the discussion :)

**Comment by adrien-thierry** [comment]
@kitolog i'm working on it

**Comment by kitolog** [comment]
@adrien-thierry thank you!
Would it be only functions hoisting or also variables?

**Comment by adrien-thierry** [comment]
@kitolog also variables

**Comment by adrien-thierry** [comment]
Function use before definition is now allowed : 683bf48 (v0.6.64)

`nectar --run example/functions.js`

`cat example/function.js` :
`
hello();
function hello()
{
    console.log("Hello !");
}
`

I will add the same behavior for vars

**Comment by adrien-thierry** [comment]
Function and var hoisting is now enabled for global scope : e7052d3 (v0.6.66)

`nectar --run example/hoisting.js`
