### ISSUE TITLE
xx/.nectar/j4zfc/app/src/main/cpp/native-lib.cpp:73:53: error: use of undeclared identifier 'android'

### ISSUE THREAD

**Issue by lancasterJie** [NectarJS/nectarjs#87]
Hi everyone,  I am trying to compile js code to target android platform. Well, I have installed android-sdk-28,  ndk-21,cmake 3.10.2, on ubuntu 20.  One error happen when I run nectar test.js --env android, ".nectar/j4zfc/app/src/main/cpp/native-lib.cpp:73:53: error: use of undeclared identifier 'android'," and I stuck on this error all day long ~ appreciate anyone can help me~ 

detail: 
 What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/jieren/android/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/jieren/node/.nectar/j4zfc/app/.cxx/cmake/debug/armeabi-v7a native-lib}
  ninja: Entering directory `/home/jieren/node/.nectar/j4zfc/app/.cxx/cmake/debug/armeabi-v7a'
  [1/2] Building CXX object CMakeFiles/native-lib.dir/native-lib.cpp.o
  FAILED: CMakeFiles/native-lib.dir/native-lib.cpp.o
  /home/jieren/android/ndk/r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi19 --gcc-toolchain=/home/jieren/android/ndk/r20/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/jieren/android/ndk/r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -Dnative_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/native-lib.cpp.o -MF CMakeFiles/native-lib.dir/native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/native-lib.cpp.o -c /home/jieren/node/.nectar/j4zfc/app/src/main/cpp/native-lib.cpp
  /home/jieren/node/.nectar/j4zfc/app/src/main/cpp/native-lib.cpp:73:53: error: use of undeclared identifier 'android'
      __NJS_Call_Function(__NJS_Object_Get("onEvent", android), nString);
                                                      ^
  1 error generated.
  ninja: build stopped: subcommand failed.

**Comment by adrien-thierry** [comment]
Hi @lancasterJie 
Thank you for reporting the issue, it's my Bad, i unified the `android` and iOS API with the same object : nectar

So, replace `android` by `nectar` and it should work

**Comment by lancasterJie** [comment]
> Hi @lancasterJie
> Thank you for reporting the issue, it's my Bad, i unified the `android` and `iOS` API with the same object : `Nectar`
> 
> So, replace `android` by `Nectar` and it should work

Hi @adrien-thierry 

Thanks for your reply, it works. 
Well, is there any other way to modify once and can work for anywhere.
The error still comes out when I use official nectar t.js -env android, and then I need to change __NJS_Call_Function(__NJS_Object_Get("onEvent", android), nString); to 'Nectar'    and run ./gradlew build to generate the apk,
it's kind of too complicated. Thx a lot~

**Comment by lancasterJie** [comment]
Finally  solved, we need to change the 
1. /usr/local/lib/node_modules/nectarjs/compiler/native/platform/android/app/src/main/cpp/native-lib.cpp 
__NJS_Call_Function(__NJS_Object_Get("onEvent", android), nString); to
__NJS_Call_Function(__NJS_Object_Get("onEvent", Nectar), nString); 

2. xxx/compiler/native/squel/android.cpp
__NJS_Call_Function(__NJS_Object_Get("onEvent", android), nString); to
__NJS_Call_Function(__NJS_Object_Get("onEvent", Nectar), nString); 

These changes work for me~

**Comment by lancasterJie** [comment]
> Hi @lancasterJie
> Thank you for reporting the issue, it's my Bad, i unified the `android` and `iOS` API with the same object : `Nectar`
> 
> So, replace `android` by `Nectar` and it should work

@adrien-thierry 
Thanks for your reply, it works for me~

**Comment by adrien-thierry** [comment]
@lancasterJie , i updated the NPM version, version 0.6.67 should work without problem

**Comment by adrien-thierry** [comment]
Can you confirm that is working out of the box ?

Did you try the embeded http server with Android ?
