### ISSUE TITLE
Path to file can't contain spaces, parenthesis, etc

### ISSUE THREAD

**Issue by raguay** [NectarJS/nectarjs#88]
The compiler will die if the path to the file isn't plain text without spaces, parenthesis, etc.

macOS 10.15.5

**Comment by adrien-thierry** [comment]
Hi @raguay ,

Thank you for the issue, i will correct this

**Comment by adrien-thierry** [comment]
It should be corrected for std env in v0.6.69, I added an example named "with space.js" 

I will improve this behavior by checking if the path contains `"` or not
