### ISSUE TITLE
Can I compile Javascript code to arm64 executable file?

### ISSUE THREAD

**Issue by lancasterJie** [NectarJS/nectarjs#89]
Hi, 
Nectar supports Android and Linux std. Can I change g++ to arm-linux-gnueabi-gcc?  So I can compile JS on Linux PC and output the executable file that can be ran on arm64 mobile platform (with adb shell) ?
Thanks alto

**Comment by adrien-thierry** [comment]
Hi,

Yes, you can, the STM32 env uses gcc-arm-none-eabi to cross compile, you can change the default compiler by the one you want with :

`nectar --compiler "arm-linux-gnueabi-gcc" file.js`

**Comment by adrien-thierry** [comment]
I will also add the possibility to select a custom env file to make it easy to customize env

**Comment by adrien-thierry** [comment]
@lancasterJie is it ok ?

**Comment by lancasterJie** [comment]
> @lancasterJie is it ok ?

Yes, it works, thanks a lot. 
Nectarjs is so cool~
