### ISSUE TITLE
How do you deal with the need for type information?

### ISSUE THREAD

**Issue by ColinEberhardt** [NectarJS/nectarjs#9]
Other projects that compile JavaScript (or JavaScript-like languages such as TypeScript) require the addition of types to your code in order to allow compilation.

Does NectarJS have the same requirement?

Or do you somehow infer types through static analysis?

**Comment by adrien-thierry** [comment]
Hi,
others projects (TypeScript, CoffeeScript ...) don't really "compile" JS, they transpile a sub-language in JS.

Regarding NectarJS, you don't need to add type, we are using static analysis and dynamic algorithms to manage it. We are working hard on this part

You can discuss with us on slack : http://api.nectarjs.com:3000/

**Comment by ColinEberhardt** [comment]
I was meaning projects like AssemblyScript, TurboScript and speedyjs, that compile to wasm, rather than TypeScript that transpiles to JS.

It’s interesting that you project doesn’t require the addition of type information to make compilation possible. I assume it will have some limits as JS developers do sometimes ‘juggle’ types.

**Comment by adrien-thierry** [comment]
We are trying to unlock all limits, right now types are dynamics so you can do that : 

```
var obj = { _int: 1, _string: "string"};
console.log(obj._int);
obj = "a string";
console.log(obj);
```
