### ISSUE TITLE
Project needs better documentation

### ISSUE THREAD

**Issue by tobimensch** [NectarJS/nectarjs#93]
I just discussed this project with some other people on IRC and all agreed that this project is underdocumented.

Things that are missing:
- A clear roadmap or communication of specific project goals. For example, is the goal to be ES3 compatible, or does it intend to be ES5 compatible as well?
- Guide on how to contribute to the project, that explains how different bits of the project relate to each other, and what the best practices are (and why). Which areas are best suited for contributions?
- Documentation of the current limitations, and some hints on how those might get lifted (if ever).
- What are the differences compared to ts2c? Why should one choose nectarjs over ts2c? (And why not collaborate more?)
- What specific goals are funds going towards?
- Details, details, details. For example, you wrote that you're now using your own memory management implementation, but it's important to know the details of that solution and why you chose it.  It's not a great idea to hide such information, or to write it only in a blog format, it needs to exist in the main documentation of the project.

I'll definitely keep an eye on this project, as it seems like a lot of processing power is wasted, and I don't understand why the big guns (Google, etc.) didn't come up with something like it.

**Comment by adrien-thierry** [comment]
Hi @tobimensch , thanks for your recommendation, i will write more documentation

**Comment by tobimensch** [comment]
@adrien-thierry 
Great!

One reason why I became interested in nectarjs is because I'd like to be able to use https://asciidoctor.org/docs/asciidoctor.js/ inside non-javascript project (C++ or Nim).

Ironically you could use asciidoctor to improve your documentation, it's a well defined format, that fixes a lot of the shortcomings of markdown and other such formats. There are two versions asciidoc (written in python2/3) and asciidoctor, which is written in Ruby, and Ruby can be translated to JavaScript using Opal (asciidoctor.js is the result of that). I'd like to be able to use asciidoc in my projects, without having to install either a python, ruby or javascript interpreter. And it seems like nectarjs could be the solution for that.

**Comment by adrien-thierry** [comment]
Yes, I totally agree.

In fact, we will be able to compile a lot of things : typescript, python, ruby ... For a lot of platforms.

I didn't develop more the doc now because i really wanted to focus on making it work good. Now the memory management is stable and we started to use NectarJS in production projects. 

So yes, the logical next step is a great doc.

**Comment by adrien-thierry** [comment]
@tobimensch don't hesitate to join us on discord

**Comment by tobimensch** [comment]
@adrien-thierry 
I'm usually on IRC irc.freenode.org . Maybe you can start a channel there? Lots of developers are on freenode.

**Comment by adrien-thierry** [comment]
Updated with code of conduct and contributing,

I'm adding the developper doc

**Comment by adrien-thierry** [comment]
irc : https://kiwiirc.com/client/irc.freenode.net/#nectarjs

**Comment by adrien-thierry** [comment]
bridge irc <-> discord is up

**Comment by adrien-thierry** [comment]
Doc started: https://nectarjs.com/documentation

I will add more info about memory management, platforms and roadmap

**Comment by tobimensch** [comment]
@adrien-thierry 
I think the bridge is not working, there's a bot in this IRC channel, but nobody else can be seen.

**Comment by tobimensch** [comment]
For the record. @adrien-thierry fixed it. Thanks.
