### ISSUE TITLE
Builtin objects don't have prototypes

### ISSUE THREAD

**Issue by sudo-carson** [NectarJS/nectarjs#97]
A very common snippet used in many JS frameworks is `Array.prototype.slice.call`, which does not run with Nectar (not because of the .call, that's for another issue). Builtin objects like Array, Object, Number, etc. should have prototypes.

**Comment by adrien-thierry** [comment]
Hi @sudo-carson , thank you,

I'm working on making protypes ES3 compliants, i will send updates

**Comment by Saiv46** [comment]
@sudo-carson Prototype support is almost ready, but builtins object methods is still being working on.

**Comment by adrien-thierry** [comment]
@sudo-carson `Array.prototype.slice.call` is working, we now have to write all the Builtin objects functions

You can check example/array.js 

All objects have a prototype property now, and it's possible to use call on all functions
