### ISSUE TITLE
Can I get the timestamp in millisecond?

### ISSUE THREAD

**Issue by lancasterJie** [NectarJS/nectarjs#99]
Hi 
We have read your date.js demo for the current time in second and UTC.
Is there any way to get the time in millisecond?
thanks a lot 
jie

**Comment by adrien-thierry** [comment]
Hi,

The UTC timestamp should be in millisecond

**Comment by lancasterJie** [comment]
Thanks for your reply.
You are right, UTC is the milliseconds from 1970 to now.
My linux system return, UTC: Thu Aug 27 10:10:05 2020.
Now, I try to convert it to millisenconds~

**Comment by adrien-thierry** [comment]
Hi @lancasterJie ,

thank you for your feedback,

Yes, we have started to optimized some piece of code to show the potential of NectarJS.

Don't hesitate to join us on Discord if you have any questions
